name: Test

env:
  PLUGIN_NAME: redmine_text_blocks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-with-postgres:
    name: ${{ matrix.redmine }} postgres:${{ matrix.db_version }} ruby-${{ matrix.ruby }}
    runs-on: ubuntu-22.04

    container:
      image: ruby:${{ matrix.ruby }}-bullseye

    strategy:
      matrix:
        ruby: [2.7] #[2.7, 3.0, 3.1]
        redmine: [4.2-stable] #[4.2-stable, 5.0-stable, master]
        db_version: [10] #[10, 14]
      fail-fast: false

    services:
      postgres:
        image: postgres:${{ matrix.db_version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Redmine
        uses: actions/checkout@v2
        with:
          repository: redmine/redmine
          ref: ${{ matrix.redmine }}
          path: redmine

      - name: Checkout Plugin
        uses: actions/checkout@v2
        with:
          path: redmine/plugins/${{ env.PLUGIN_NAME }}

      - name: Update package archives
        run: apt-get update --yes --quiet

      - name: Install package dependencies
        run: >
          apt-get install --yes --quiet
          postgresql-client

      - name: Prepare Redmine source
        working-directory: redmine
        run: |
          cat <<EOF > config/database.yml
            test:
              adapter: postgresql
              database: redmine
              host: postgres
              username: postgres
              password: postgres
              encoding: utf8
          EOF

      - name: Install Ruby dependencies
        working-directory: redmine
        run: |
          bundle config set --local without 'development'
          bundle install --jobs=4 --retry=3

      - name: Run Redmine rake tasks
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: |
          bundle exec rake generate_secret_token
          bundle exec rake db:create db:migrate redmine:plugins:migrate

      - name: Run tests
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: bundle exec rake redmine:plugins:test NAME=${{ env.PLUGIN_NAME }} RUBYOPT="-W0"

      - name: Run uninstall test
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: bundle exec rake redmine:plugins:migrate NAME=${{ env.PLUGIN_NAME }} VERSION=0
