name: Test with SQLite

env:
  PLUGIN_NAME: ${{ github.event.repository.name }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.redmine_version }} ruby-${{ matrix.ruby_version }} sqlite
    runs-on: ubuntu-22.04

    container:
      image: ruby:${{ matrix.ruby_version }}-bullseye

    strategy:
      fail-fast: false
      matrix:
        redmine_version: [4.2-stable, 5.0-stable, master]
        ruby_version: [2.7, 3.0, 3.1]
        exclude:
          - redmine_version: 4.2-stable
            ruby_version: 3.0
          - redmine_version: 4.2-stable
            ruby_version: 3.1

    steps:
      - name: Checkout Redmine
        uses: actions/checkout@v2
        with:
          repository: redmine/redmine
          ref: ${{ matrix.redmine_version }}
          path: redmine

      - name: Checkout Plugin
        uses: actions/checkout@v2
        with:
          path: redmine/plugins/${{ env.PLUGIN_NAME }}

      - name: Update package archives
        run: apt-get update --yes --quiet

      - name: Install package dependencies
        run: >
          apt-get install --yes --quiet

      - name: Prepare Redmine source
        working-directory: redmine
        run: |
          cat <<EOF > config/database.yml
            test:
              adapter: sqlite3
              database: db/redmine.sqlite3
          EOF

      - name: Install Ruby dependencies
        working-directory: redmine
        run: |
          bundle config set --local without 'development'
          bundle install --jobs=4 --retry=3

      - name: Run Redmine rake tasks
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: |
          bundle exec rake generate_secret_token
          bundle exec rake db:create db:migrate redmine:plugins:migrate

      - name: Zeitwerk check
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: |
          if grep -q zeitwerk config/application.rb ; then
            bundle exec rake zeitwerk:check
          fi
        shell: bash

      - name: Run tests
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: bundle exec rake redmine:plugins:test NAME=${{ env.PLUGIN_NAME }} RUBYOPT="-W0"

      - name: Run uninstall test
        env:
          RAILS_ENV: test
        working-directory: redmine
        run: bundle exec rake redmine:plugins:migrate NAME=${{ env.PLUGIN_NAME }} VERSION=0
